
describe "Thin_Upstart.trash" do
  
  it "removes all files with string: # Generated by Thin_Upstart" do
    chdir {
      Multi_0 %@
        mkdir trash
        echo "# Generated by Thin_Upstart (Ruby gem)" >> trash/1.conf
        echo "# Generated by Thin_Upstart (Ruby gem)" >> trash/2.conf
        echo "# Generated by Thin" >> trash/3.conf
      @

      Thin_Upstart.trash "trash"
      File.file?("trash/1.conf").should == false
      File.file?("trash/2.conf").should == false
      File.file?("trash/3.conf").should == true
    }
  end
  
end # === Thin_Upstart.trash

